"""Create relationship

Revision ID: 785fe198c50c
Revises: c3db6a5c0fb3
Create Date: 2024-05-15 23:03:55.333787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "785fe198c50c"
down_revision: Union[str, None] = "c3db6a5c0fb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "groups", ["group_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="unique")
    # ### end Alembic commands ###
