Student: {
  shape: sql_table

  id: int {constraint: [primary_key; unique]}
  first_name: str
  last_name: str
  group_id: int
}

Group: {
    shape: sql_table

    id: int {constraint: [primary_key; unique]}
    group_number: str
    students: "list[int]"
}